### PR TITLE
[irobot] Minor readme corrections

### PR DESCRIPTION
**Pull request by kennetn**
Minor clarification originally described here https://community.openhab.org/t/irobot-9xx-on-openhab/17774/196
Signed-off-by: Kennet Nielsen <kennetn@gmail.com>

### CODE REVIEW

**Comment by falkena** [comment]
Hi @kennetn. Thanks for your PR. You raised a PR against my fork: is it on purpose?

**Comment by kennetn** [comment]
Well I was a unsure if it was better to do it towards your fork or the main one.
So I just started with doing it towards your repo :-)

**Comment by falkena** [comment]
Ok. I see. It's always better to raise a PR against main repo. This way the community will get your changes and not only me. Normally forks will be rebased from time to time against main repo. I do the same. I'll get your changes this way.

**Comment by kennetn** [comment]
Will try and do a pull towards main instead

**Pull request closed without merging**
